# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  options: --platform arm64  # 参数说明：https://docs.docker.com/reference/cli/docker/container/create/

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    uname -r && uname -a
  displayName: 'Run a multi-line script'
